### ISSUE TITLE
Promoting FetLife Android App

### ISSUE THREAD

**Issue by kistitan** [fetlife/android#117]
Based on feedbacks still many user look for FetLife App in Google Play Store.

I could add a feature toggle to the App code so we could generate each time a lite and a full version.
Lite version could contain only resources acceptable by Google Play Store with a link to the full version.

**Comment by kistitan** [comment]
@johnbaku

**Comment by malachid** [comment]
When Google banned us, they told us it was because we had links to fetlife.com. They said they would respond to any attempt to republish by deleting our google accounts.

**Comment by FernandoMiguel** [comment]
@malachid and they will do it... it's a terrible habit they got!

**Comment by kistitan** [comment]
Great comment, thanks a lot!
Hmm... it makes it more difficult. 

I wonder if they would accept the FetLife logo without any actual link followable by the user.
Whiplr is also a kinky app but available for a while at the play store.

**Comment by malachid** [comment]
We were in the top 10 for 2-1/2 years then they took us (and quite a few other apps) down just a few weeks after announcing Google Play for Education.  I believe it was an effort to clean up the image of the play store to be safe for kids. My understanding is that while some apps were still there, it was just a matter of time until they were noticed.  We were probably noticed quicker because we were on the front page.

As far as links go - they will try to use the app and watch for network usage.  If it uses the fetlife API, that would count as linking to fetlife.com (that's what we were doing).  If you were to use a proxy to circumvent it, that would be breaking their TOU.

When we were kicked off, MiKandi offered to host us, but it didn't seem like the community was really onboard with that solution.  

The best option is for it to be presented on the FetLife website proper (direct link to APK) to any website user; and also recommended to Android users coming in via mobile browser.

**Comment by FernandoMiguel** [comment]
@malachid the issue of having APK installed from Unsecure Sources, is exposing the device to risk of malware infected apps.
Google Ecosystem is setup to prevent users from doing so.

I understand both sides of the problem, just trying to convey their reasoning

**Comment by kistitan** [comment]
@malachid I see.. so it very much seems to be no go...

I really hoped that they allow a normal chat app even if the registration is actually connected to FetLife.

**Comment by malachid** [comment]
@FernandoMiguel completely understand - I did the same.
@kistitan I agree. It's not the devs. There were devs at Google and various OEMs that were using our app and asking permission to test it on new hardware. It's really unfortunately that they blacklisted us.

**Comment by johnbaku** [comment]
After dealing with trying to get our iOS app in Apple's iOS store I really don't want to play a cat and mouse game with the Google's and Apple's of this world! It won't be fun and will just kill morale and progress.

I also understand and respect where both Google and Apple are coming from and think we should respect their decisions. No matter how frustrating it might be. 

Instead what I want to do is promote this app through our upcoming new logout screen:

<img width="1280" alt="we_ll_miss_you___fetlife" src="https://cloud.githubusercontent.com/assets/22100/17112259/2c3c3226-525a-11e6-9f4e-7e12a06f0366.png">

It won't be as easy for people as the app being in the app store... BUT... I think it will make a huge difference.

What say you?

**Comment by malachid** [comment]
I don't personally ever log out.

**Comment by johnbaku** [comment]
@malachid yeah... that definitely won't be for everyone... but their are tons of people who do.

**Comment by FernandoMiguel** [comment]
Folks logout so others don't have access to their profile

**Comment by GojuSuzi** [comment]
I think it's be good to have a link to wherever it winds up being hosted long-term in the burger menu on the home page. There's a "Need help?" bit there that leads to a sort of idiot's guide, and sticking a "Get the app!" next to that would work, since it's the first place you'd look for things that aren't immediately on the front page, but is unobtrusive enough that folk won't be badgered about it every time they refresh their feed.

**Comment by johnbaku** [comment]
@GojuSuzi I do agree it needs to be their as well.

**Comment by JayKeelz** [comment]
The ad on the login page or sidebar seems to be the most ideal placement. Unobtrusive and what a great number of users would expect.

**Comment by kistitan** [comment]
@johnbaku @reneklacan 
Do you think it is time for a next promotion round?
Adding a link to the sidebar, etc...

**Comment by johnbaku** [comment]
@kistitan definitely an option. Hit me up so we can talk about it.

**Comment by kistitan** [comment]
Topic is closed as it is duplicated with an internal discussion

**Comment by Xenophile426** [comment]
I can also get it in the Google store. I have a developer license :)

**Comment by Xenophile426** [comment]
dude, Pornhub.com has an app there. fetlife.com is not nearly as dirty, you just have the right security.

**Comment by Xenophile426** [comment]
@kistitan hey count me in as a volunteer to help code, and get around security. it's what I do for a living :)
