### ISSUE TITLE
Confirmation Prior to Logout

### ISSUE THREAD

**Issue by Daddy** [fetlife/android#122]
**Scenario**
As a FetLife Android app user,
I may occasionally accidentally tap the Log Out menu item while intending to click elsewhere,
and be forced to log back in.

**Suggested Outcome**
Have a "Are you sure you'd like to Log Out?" confirmation dialog appear prior to logging the user out of the application, to ensure they want to close the current session.

References #120.

**Comment by kistitan** [comment]
Hmm...
Thanks for reporting.
It can be indeed annoying.

On the other hand personally would be bothered by an additional confirmation. 
Especially because it is not something you can not restore.
But might be something that is important for others too so let's keep it open and see how others think about.

**Comment by FernandoMiguel** [comment]
personally I dont see the need for confirmation

**Comment by kistitan** [comment]
Because of the recent changes and planned menu restructuring this probably won't be needed
