### ISSUE TITLE
Opening emails slow

### ISSUE THREAD

**Issue by restrainedimages** [fetlife/android#167]
When I click on an email alert it is very slow to open.
If I open the app and there is a new reply to an existing conversation then when I open it the reply isn't displayed. It is clearly retrieving it but it takes ages.

I'm on WiFi and have opened the message in a browser while waiting. So I don't think it is network performance.

Could a large number of messages in the inbox be the cause?

Is anyone else getting anything similar?

**Comment by reneklacan** [comment]
@restrainedimages can you please tell us what phone do you use and result of https://fast.com/?

**Comment by malachid** [comment]
I'm seeing the same thing on the most recent version. LG v10. Fast says 76mb/s.

**Comment by malachid** [comment]
Seems to be a refresh issue. It spins indefinitely without loading. If you hit back and reopen it, the conversation is shown and it still shows loading indefinitely. No exceptions are listed in logcat.

**Comment by GojuSuzi** [comment]
Same thing. Nexus6 on 6.0.1, that speed test is running 51mb/s currently (WiFi and same as prior to issue presenting, only since last update).

As well as the never-ending spinner top right, even after the combo loads:
* Sending a message shows as grey forever, as if it hasn't sent, until you go back out of the combo and back in;
* No matter how many times reading, exiting, re-entering convos, they still have the new flag, and in the browser count as unread;
* When you enter a convo after opening the app, it will load all the new-since-last-app-update messages one by one, so the oldest new, then next, then next, which isn't bad if it's two or three, but will soon get a bit of a PITA;
* If in a browser page opened from an app notification, and then hitting 'back', it 'forgets' who you are, and despite being logged in with always-ask de-checked, pops a log-in.

It does just seem to be suffering some kind of short-term amnesia since the last update over all. Very odd, and all only since 1.5.11

**Comment by kistitan** [comment]
There were several structural changes in 1.5 version.

I faced the same issue for a period without version change.
I am investigating what caused it. 
I keep you updated.

Thanks a lot for helping us testing!

**Comment by restrainedimages** [comment]
My situation is similar to @GojuSuzi except the speed test only showed about 39Mbps.

I've experienced all the additional scenarios / issues too. I just hadn't understood them clearly enough to document them that well. It felt like dodgy internet connectivity. It was only when I ruled that out I started to suspect more serious issues.

J

**Comment by kistitan** [comment]
Ahh so stupid...
An important code line was accidentally deleted after local testing.

So the service ran correctly but the UI was not notified, so neither the message lost nor the spinner was updated.

New version with fix will be releases soon.

Thanks a lot again and sorry for the inconveniences.

**Comment by kistitan** [comment]
Hi all,

Can you please start testing v1.6.1.

Issue (together with several other should be solved).

Feel free to reopen if it occurred again.

**Comment by GojuSuzi** [comment]
Just to confirm, none of the problems presenting as of 1.6.1.

**Comment by malachid** [comment]
Confirmed fixed in 1.6.1
