### ISSUE TITLE
privacy notifications

### ISSUE THREAD

**Issue by FernandoMiguel** [fetlife/android#187]
I've got my android set to not show details of notifications on the lockscreen.

fet app does not follow this setting and shows the details of the notifications on the lockscreen.

within its options , if enable anonymous notifications, that will prevent me to see what i got even when screen unlocked.

https://support.google.com/nexus/answer/6111294

**Comment by kistitan** [comment]
@FernandoMiguel 
Thank you for letting us know.
As of now FetLife App has it is own setting for anonymous notifications that is a bit broader than the nexus setting, that's why we decided to have a separate one.

I will check if we have an option to set it automatically if you use your device setting.
In the meanwhile please set it also in the app's settings.

Thanks again for supporting us

**Comment by thezerogod** [comment]
Just wanted to add to this, in case it's fallen off the radar. Current production version of the app, Android 7.1.1, Nexus 6. System setting (Settings > Notifications > Configure Notifications (gear in upper-right corner)) or "on the lock screen" is "Hide sensitive notification content".

Other apps (e.g. Signal, Twitter, Gmail) show the name of the app, then the message "Contents hidden". This is my desired setup for all apps.

The FetLife app ignores this setting and shows (for example), "FetLife, DEVIANToronto, New discussion was started"

I like having notifications on my lock screen, but would also like it if the FetLife app respected this system setting.

Screenshot attached.

![screenshot_20170213-124054](https://cloud.githubusercontent.com/assets/2320654/22895286/e7944458-f1e9-11e6-9aab-397975990363.png)

**Comment by FernandoMiguel** [comment]
I've asked for that weeks ago, before they merged with vanilla version, and was told this wasnt going to change :(

it's said, cause it's the only app on my phone that is not following my privacy settings, and exposing sensitive details

**Comment by thezerogod** [comment]
From a quick review of the notifications code at [https://github.com/fetlife/android/blob/master/FetLife/fetlife/src/main/java/com/bitlove/fetlife/notification/OneSignalNotification.java](url), I'm guessing that part pf the reason for this is that they're using OneSignal notifications instead of the default Notification.Builder from the Android SDK. Regardless, it looks like there's an option that can be configured in the notification payload that should make the notification respect the system's global privacy settings:

The OSNotificationPayload class [https://documentation.onesignal.com/docs/android-native-sdk#section--osnotificationpayload-](url) contains an int parameter called lockScreenVisibility described as follows:
	
Privacy setting for how the notification should be shown on the lockscreen of Android 5+ devices.
1 (DEFAULT) - Public (fully visible)
0 - Private (Contents are hidden)
-1 - Secret (not shown).

In the code, this might look like this (see the last line in this snippet):

    public OneSignalNotification(String title, String message, String launchUrl, JSONObject additionalData, String id, String group) {
        this.title = title;
        this.message = message;
        this.launchUrl = launchUrl;
        this.additionalData = additionalData;
        this.group = group;
        this.id = id;
        this.lockScreenVisibility = 0;
    }

However, I think that hard-coding the "0" in there would disrupt people who don't mind that this data is shown on their lock screen. Perhaps there is a way to configure this with an option in the app? If not, would anyone mind giving me a very brief overview of why OpenSignal was used instead of Notification.Builder so I can consider the merits of rewriting the notification function with native classes?

**Comment by kistitan** [comment]
Hi @thezerogod ,

Thanks a lot for the investigation.
Indeed having native code always give the option of having full control. however it has the drawback of increased maintenance and development time.
Let we check together with OS guys what can we do.

**Comment by kistitan** [comment]
Hi all,

I played a bit around with this, and indeed the main settings is ignored, but if you set it on App level at general device settings it works for me perfectly.

Can you confirm this?
If this works at least in app setting would be unnecessary for sure.

**Comment by kistitan** [comment]
Gotcha... OneSignal use indeed Public visibility by default instead of default android Private.
Managed to override.

Will be fixed in next version.

**Comment by FernandoMiguel** [comment]
yay

**Comment by thezerogod** [comment]
Amazing, great work!

On 2017-02-16 8:05 AM, kistitan wrote:
> > Gotcha... OneSignal use indeed Public visibility by default instead
of default android Private. > Managed to override. > > Will be fixed in
next version. > > — > You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
<https://github.com/fetlife/android/issues/187#issuecomment-280325185>,
or mute the thread

**Comment by kistitan** [comment]
Code changes added to version 2.5.8.
It should work now, but feel free to reopen if it does not.
