### ISSUE TITLE
FetLife Formatting Guidelines, can we have them please?

### ISSUE THREAD

**Issue by steelowheel** [fetlife/android#193]
FetLife Formatting Guidelines, can we have them please? These: https://fetlife.com/formatting_guidelines

**Comment by kistitan** [comment]
Hi @steelowheel,

You mean for the messages?

**Comment by steelowheel** [comment]
Hey @kistitan 

Yes, for the messages.

**Comment by reneklacan** [comment]
@kistitan maybe you can utilize something like https://github.com/geminiwen/gm-mkdroid ?

**Comment by johnbaku** [comment]
@reneklacan and @kistitan I would personally like to move away from markdown or hide markdown from people and use a sort of WYSIWYG editor.

**Comment by kistitan** [comment]
I agree that we should reconsider markdown.
It would like very... strange in a chat functionality of a mobile app.

Some kind of formatting option however can be indeed useful.

**Comment by kistitan** [comment]
@steelowheel

Thank you for reporting this request.
It is indeed an interesting one, but we should ask for your patience as we should think about our long term strategy about message formatting and design principle differences in the web and the app world.

Thank you for your understandings

**Comment by kistitan** [comment]
I close this now, as any further todos is depends on the strategy we are going to follow with the general message formatting. 
Thank you

**Comment by ReluctantSub** [comment]
@kistitan 
I know this was just closed a few seconds ago, but kistitan, can you please look here:
https://fetlife.com/groups/693/group_posts/9440963

**Comment by kistitan** [comment]
Hi @ReluctantSub , 

I see your point so I reopen this issue for now, until we can open a better one.
I think it is pretty unlikely that we will support the same formatting guidelines that we have now in the App. It would not make much sense.
However I it might make sense to go through some common use cases for that we can add some temporary workaround until we have the final strategy for this.

Thank you for adding this comment

**Comment by steelowheel** [comment]
Thanks @kistitan and @ReluctantSub 

With this thread I don't actually speak out for how I want to write and format my messages in mobile - I'm sure you have better insight in this matter. I'm only interested to see the formattings my peers use. They use the current FetLife Formatting Guidelines and I only want to see my friends' messages the way they intend to.

**Comment by CyBradMachina** [comment]
To this train of thought the formatting options should be synced btwn app and site. For example i respond to a thread with formatting options used in app but they don't translate to website and vica versa if you do it on website it doesn't translate the same to the app view of exact same location

Is there a way to fix this fluidly?

**Comment by toxalot** [comment]
@johnbaku wrote:

> I would personally like to move away from markdown or hide markdown from people and use a sort of WYSIWYG editor.

Would this be for the app only or for the website also?

@kistitan wrote:

> I think it is pretty unlikely that we will support the same formatting guidelines that we have now in the App. It would not make much sense.

I think the formatting needs to be consistent so that formatting in one does not appear as code in the other. And not just for messages, but also group posts, and group rules, and profiles, and any other written content that is added to the app. I just downloaded the app and was rather horrified to see that my profile, group posts, and event descriptions display all the code.

Please, please don't remove user formatting from the website. Formatting is a *big* part of clear written communication.

If you move to a WYSIWYG editor, please allow a code view at the very least. And please leave the code as Markdown.

* I write offline in a text editor and save backup copies of my writings. I can't copy and paste to or from a WYSIWYG editor and maintain my formatting.
* Reading text in code view is much easier with Mardown than say BBcode or HTML.
* The Markdown that you currently allow is simple enough for even less tech-savvy people to figure out with a bit of practice.

@kistitan wrote:

> I agree that we should reconsider markdown. It would like very... strange in a chat functionality of a mobile app.

I understand not wanting formatting in a chat feature. That's all the more reason to keep chat and private messaging as two separate features. They serve very different purposes and require different options. It's like the difference between text and email.

**Comment by kistitan** [comment]
After long time this will appear in the App, automatically as we are going to use webviews to display content what will be the same as at the website.
Closing this for now.
