### ISSUE TITLE
Notifications not showing up. 

### ISSUE THREAD

**Issue by PixelPolish** [fetlife/android#199]
I'm not getting any notifications on Galaxy S4, running Android 5.0.1

All notifications are turned on within the app itself,  anonymous option unchecked. On the app list the  notifications are also turned on.

**Comment by kistitan** [comment]
Hi @PixelPolish 

Thank you reporting this issue.
It is not an easy issue to investigate as our notification system rely on Google Cloud Messaging on that we have not much overview.

In generally we know that certain wifi settings can block GCM so our first suggestion is to check if the issue occurs on different networks also.

Sometimes if there are two many messages pending it can happen that they are in significant delay or lost. In these case also a phone restart can help sometimes.

If neither of this helps all we can do is to create a special debug build for you and we start testing together with monitoring our system in the meanwhile.

Please let us know how does it go.

**Comment by PixelPolish** [comment]
Hej @kistitan 

A little update: seems like I wasn't getting any notifications at work, but I do get them at home (not sure about 4G only yet). Are those supposed to make any sound? Not sure if I just missed it or are they silent.

**Comment by kistitan** [comment]
@PixelPolish 
I am afraid it is more likely that you did not receive them.

Many corporate wifi has some kind of blocking mechanism for Google Cloud Messaging.
Based on my experience sometimes it is not even intentional.
If you can talk to the system administrator you might can ask if (s)he has any idea about it.

We have plan to have some kind of fall back for polling notifications, but this won't happen in short term as it need significant design work.

Keep us updated how it goes...

Thank you

**Comment by PixelPolish** [comment]
Nah, it's a small company with home-like network settings, so it shouldn't be a problem. As for the "silent" notifications, I did get them, just didn't hear them coming. But as I've said, might have just somehow missed them. It would help if I could set a custom sound for FL.

**Comment by kistitan** [comment]
@PixelPolish
I am happy it is now clarified.
Thanks for your suggestion. We already have a lower priority issue open for customizable notifications.
So I closed this issue now.

Thanks again.
