### ISSUE TITLE
New message

### ISSUE THREAD

**Issue by CrowandButterfly** [fetlife/android#205]
When I try to read a message it opens in a new window. Only started after the last update.  Can't click on user profile from there either.

**Comment by FernandoMiguel** [comment]
ah i see what you mean...
if you click the avatar, it opens the site profile.

if you click to the right, it opens the message

**Comment by CrowandButterfly** [comment]
Not for me, and I also can't start a new message with someone I'm not friends with.


Sent from my Sprint Samsung Galaxy S® 6.
-------- Original message --------From: Fernando Miguel <notifications@github.com> Date: 11/4/16  3:59 PM  (GMT-05:00) To: fetlife/android <android@noreply.github.com> Cc: CrowandButterfly <crow.butterfly11@gmail.com>, Author <author@noreply.github.com> Subject: Re: [fetlife/android] New message (#205) 
ah i see what you mean...

if you click the avatar, it opens the site profile.

if you click to the right, it opens the message

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fetlife/android","title":"fetlife/android","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/fetlife/android"}},"updates":{"snippets":[{"icon":"PERSON","message":"@FernandoMiguel in #205: ah i see what you mean...\r\nif you click the avatar, it opens the site profile.\r\n\r\nif you click to the right, it opens the message"}],"action":{"name":"View Issue","url":"https://github.com/fetlife/android/issues/205#issuecomment-258532691"}}}

**Comment by FernandoMiguel** [comment]
yeah, i see what you mean now.
the app should open a new message from friends, not open their profile.
hope the team can look this up

**Comment by kistitan** [comment]
@CrowandButterfly 

Hi there,

Thank you for opening this issue and also for starting the thread on FetLife.
We are sorry for the confusions that the app caused.

Please let me clarify the three mentioned issues that popped up here (and at the FetLife forum thread)

**Starting a conversation with friend:**
Starting a new conversation with a friend cannot be started from the friend screen in current version. To start a new conversation please use the floating button from the conversations screen that will open a list of friends (similar to the friends screen but with different title) where you can select which friend you would like to start a conversation with.

Using the floating action button pattern for creating a new conversation is default android pattern but it sometimes causes some confusion so we probably going to change this in the upcoming 2.0 version of the app. So in the future you will be able to start a new conversation (also) from your friend list. 

**Remember me vs Always ask for my password**
This confusion is already caused some headache to some users and it is personally my fault.
I added this way because in technical level this term is closed to the actual solution however from user perspective there is no difference in the actual use cases, so we should have aligned with the website and use the checkbox the other way around.
We plan to change this too in the upcoming 2.0 version.

**Starting a conversation with a user who is not a friend.**
This is very important enhancement and it is on our future plans however for this we should implement several other complex features first: like in app profile screen and search functionality. 
These are also our todo list but before them we would like to finish with out higher priority tasks like the activity feed.

I keep this story open as a feature request for the described functionality above.

Thanks you very much for you patience and for supporting us with your ideas and remarks.

**Comment by kistitan** [comment]
To make it more readable I close this issue now and open a new one for:
Starting a conversation with a user who is not a friend.

Thank you

**Comment by malachid** [comment]
Please leave a reference to the new ticket number whenever you do so.
