### ISSUE TITLE
Login Screen - change in meaning of control

### ISSUE THREAD

**Issue by scottfurry** [fetlife/android#209]
Have latest version installed (v1.7.20)
Android Lollipop (v5.0)
Prior release login screen had check box with "Remember me" allowing users to not have to re-enter password.
Current release uses same control but inverts the meaning. Not checking means always allow future logins w/o User Name/Password. That, IMHO, is inconsistent to other "security conscious" sites where check means to remember. Also, a security hole, again IMHO, that users should EXPLICITLY enable security.
Security by default; hole by choice.

**Comment by kistitan** [comment]
Hi @scottfurry,

Thank you for reporting this issue and sorry for the delay in answering.
We are working on 2.0 to get it ready sooner than later.
This is issues has been already causing some confusion with other users so we are going to change it in the 2.0.

Please note: security and privacy is our first priority.
That's why default value for "Always ask for password" is true.
After we are going to change it "Remember me" the default value will be false of course.

Side note about the background:
The reason why we started differently is because this approach is actually closer to the technical solution, however of course user experience is more important in this point so no question we should match with the website.

Thanks again.
