### ISSUE TITLE
Permissions on 2.0 update asking for identity

### ISSUE THREAD

**Issue by Zorkinfot** [fetlife/android#217]
Installation of 2.0 days new permissions are "read phone status and identity"  not good.  This is going to be a problem.  There is already a thread online in the tech support group about this.  If it is valid some explanation is going to need to happen.

**Comment by kistitan** [comment]
@Zorkinfot 

Thank you very much for opening this issue:

Please see my answer from the tech support group discussion:

Hi all,

Sorry for the late reply.

So please allowe me to make a clear statment first and than to go into the details about the background of this issue.

**FetLife Android App does not need and does not explicitly ask for "Read Phone Status and Identity" permission.
We do not read any information that is connected to this permission and we do not plan to do so in the near future.**

The reason why you still see that permission during installation time caused by a very unfortunate situation.
Some time ago the developers of Android decided to improve their app permission systems so a user can select which permission does (s)he approve and which not instead of having only two options: installing the app or not.
This is a great new feature but unfortunatelly it is not automatically backward compatible with applications implemented with the previous apporach.
One part of the strategy to enforce backward compatibility for apps with older approach is to automatically add permission requests for certain permissions in order to avoid any unexpected crashes.
Some of our recent changes to support latest Android features has appearantly triggered this backward compatibility feature and the permission request was implicitly added to our App.

If you are interested more about the background of this issue you can check the technical forum threads about the issue; just like this:
http://stackoverflow.com/questions/30277242/why-is-…

If you would like to observer our meta file that is responsible for requesting permissions and make sure it does not contain any explicit request for READ_PHONE_STATE permission you can find it in our open source repository
https://github.com/fetlife/android/blob/master/FetL…
You can also ensure via GitHub that there were no recent change in the list of permissions and we never intended to ask for this particular permission.

We will investigate which of our recent changes triggered the backward compatibility feature of Android and will release a new version without this install time permission request as soon as it is possible.
In the meanwhile feel free to explicitly disable this permission in your device's application settings. FetLife App will keep working without any issues even after disabling this permission.

Finally let me thank you for all your comments and concerns about this topic.
As @johnbaku mentioned FetLife Android App is a fully open source application and it is monitored by other Android developers outside of the FetLife Team.
But aside of this we are very much commited to you to feel safe and secure while using our application.
Continiously monitoring our work and raising any question or concern you have help us a lot to achive this goal.
So keep up to good work and feel free to ask any further question in connection with this or any other topic.

Thank you again and best regards

**Comment by kistitan** [comment]
This issue is solved in version 2.0.4.

Thank you for your patience.

**Comment by Two-Finger** [comment]
On my phone (Samsung Galaxy S4 Mini Plus, Android 4.4.4),
the "read phone status and identity" permission is still being requested, even with v2.0.4.

The three "account" related permissions are gone, though.

**Comment by kistitan** [comment]
@Two-Finger Thanks for letting us know about.

In theory it should not be done. we migrated our code to the latest OS version and added the requirements we needed by the support library.

What I can still do is to explicitly state that I don't want that permission to be added to the app.
It is kind of a workaround but it will for sure remove that permission.

Let me come back to you soon.

**Comment by kistitan** [comment]
@Two-Finger 

Can you please check version 2.0.5?

https://github.com/fetlife/android/releases/tag/v2.0.5

**Comment by Two-Finger** [comment]
This one is good :-)
Thank you!

![screenshot_2016-12-01-21-18-55](https://cloud.githubusercontent.com/assets/3533666/20808697/3bfb1778-b80c-11e6-9c57-fccf36644636.png)

**Comment by kistitan** [comment]
@Two-Finger 
Thank you too...
