### ISSUE TITLE
Unable to install 2.0 or 2.04

### ISSUE THREAD

**Issue by TheKildar** [fetlife/android#222]
Both apks download fine, but when I click to install, the permissions page on 2.0 (no new permission) & 2.04 (1new permission) both do not enable the "Install" button.  "Cancel" will highlight then act as expected.  "Install" does nothing.

Android V6.0, HTC One M8, Verizon

**Comment by TheKildar** [comment]
Last version to cleanly install was 2.0_preview

**Comment by kistitan** [comment]
Can you please turn off any dimmer or launcher app you use and try again?
Install button provided by the Operation System, so outside of our influence,

But this issue usually happens because of dimmer and launcher apps add additional overlay that has an interference with the overlay with the install button.

Please let us know the result

**Comment by kistitan** [comment]
Hi @TheKildar 

Any success in the meanwhile?

**Comment by TheKildar** [comment]
None.

The list of applications with this permission is fairly long, turning them
off one by one hasn't seemed to help. If I knew which one was causing the
issue, that would be easy. But there's no way to tell. Very frustrated.

**Comment by kistitan** [comment]
Hi @TheKildar,

I am sorry for the inconveniences.
If you managed to install 2.0.0 preview... 
Maybe have you installed a new app in the meanwhile?

Thank you

**Comment by TheKildar** [comment]
Every non-system app with write-over permission has had that permission
removed.  I still cannot install any version of FetLife (I tried the last 4
apks)

I agree that something changed.  The app isn't telling me why it won't
install (bug).

**Comment by navyguyg** [comment]
@TheKildar 

I also have an HTC. I usually use Astro File manager to access my internal files and external card. When I downloaded the update 2.0.4 I also had issues installing it since I navigated to the file on the SD card after transferring it to my phone using Astro..

I would suggest using the stock File Manager HTC has installed on their phones. 

I currently have an HTC One M9 (non rooted) and had to use this method to install the last two Fet apks, actually any apk that I have downloaded I've had to use this method. 

Hope this helps.

**Comment by kistitan** [comment]
Hi @TheKildar 

@navyguyg 's suggestion seems to be something that worth to try. 
If it does not work , maybe you can try to install any other apk from outside of an Playstore (let me know if you needed help to find one safe) if it does not work either we can make sure at least if it not FetLife App related. Of course in this case we will still try to guide you to find a solution. 
We will make sure you will have the app working :)

@navyguyg 
Thanks a lot for helping us and @TheKildar out. 
We really appreciate your help!

Have a nice day

**Comment by TheKildar** [comment]
OK, despite having rebooted several times, trying Navy guy's suggestion, I was still unable to install.

Then my phone went stone cold dead from battery drain.  Rebooted, asks installed!  I'm baffled at what would survive a restart, but I have the latest app installed.

Thanks for your help.

**Comment by kistitan** [comment]
@TheKildar 

Thank you for your reply.
Your experience helps as a lot to give advice to other users if it happens again.
