### ISSUE TITLE
Cannot install on Android 6.x with Galaxy S7

### ISSUE THREAD

**Issue by wellheeledgent** [fetlife/android#234]
Can anyone help me getting the Feltlife APK installed ? I have downloaded the APK and then started the install but it then says its not installed.
Any help ?

**Comment by FernandoMiguel** [comment]
Have you enabled Unknown Sources in settings? 
So you have any overlay app? That prevents apps from being installed

**Comment by wellheeledgent** [comment]
Hi there. Yes I have enabled unknown sources. Not sure what you mean by an overlay. I am using stock android 6.x from Samsung and I am using Touchwiz from Samsung as a launcher

**Comment by kistitan** [comment]
Hi @wellheeledgent,

Can you please disable your launcher and try again?
Launcher and dimmer apps use overlays that doesn't let install button be pressed.

Thank you

**Comment by wellheeledgent** [comment]
Hi there. How do I disable Touchwiz launcher? 
How come this only happens with this app?

**Comment by kistitan** [comment]
Hmm...
You mean you can install other apk directly?
If yes that is not the launcher/dimmer issue, because it just doesn't let you to press the install button when you try to install.
Can you confirm you have issue with pressing the install button or not?

It is not easy to see what's going wrong as until the app is installed our code is not reached.
Of course we still try to guide you.

May I ask if you tried to install the app several times and getting the same result?

**Comment by malachid** [comment]
On my devices, I download the APK via Chrome and tell it to install but it
does not succeed. I have to open it in the Files/Download app (depending on
device) and install it from there. That usually works.

**Comment by kistitan** [comment]
@malachid
Thank you for your comment.

@wellheeledgent
Can you please try this workaround?

**Comment by wellheeledgent** [comment]
Thanks everyone I just figured this out. I was trying to install the apk under my Knox application,  ie my virtual phone.  When I installed the apk in the main phone it worked fine. I was then able to manually copy the fetlife app to the knox device for security and privacy and it worked fine. Thanks everyone for helping
