### ISSUE TITLE
Suspicious activity

### ISSUE THREAD

**Issue by navyguyg** [fetlife/android#237]
Got this as soon as I installed. 
![screenshot_20161212-184600](https://cloud.githubusercontent.com/assets/22819695/21125690/490612ea-c09c-11e6-99bf-2ebeaaa2773c.png)

**Comment by malachid** [comment]
Avast reports all sideloaded apps as suspicious.  At work, I see that
pop-up every time I do './gradlew installDebug'

**Comment by kistitan** [comment]
Hi @navyguyg,

Thank you very much for reporting this.

Unfortunately as our app is not allowed in Google Play Store due to sexual content, it has to be installed manually that some apps already recognize as being suspicious. 

We can ensure that official FetLife App does not do any malicious activity. It is fully open source and are monitored by other Android experts.
We are also not aware of any fake FetLife App that are made by external developers, but if you would like to make it sure you are using the Official FetLife App, you can download it again from our GitHub page: https://github.com/fetlife/android/blob/master/README.md

If the App get installed without any issue than you are already using the official App, if you operation system warns you that the certificates mismatch and suggest you to uninstall you app before you can install the requested version, than please do uninstall it and get in contact with us ASAP. But this is very unlikely as we did not get any notification about any abused version of the FetLife App.

Thanks you again for your help and please let us know if you had any further question or concern.
