### ISSUE TITLE
Phantom notification

### ISSUE THREAD

**Issue by pappus11** [fetlife/android#243]
Kind of regularly (like almost every 2 hours), the app shows a notification "You have one or more notifications waiting" [1], but tapping on it brings up an empty Conversations screen [2] (I am also new to FL, so I don't have any conversations and the fact that it is empty is what I expect).

Going to the Notifications setting, this is also empty, and on the website I don't have notifications too.

System: Android 6.0.1 on Nexus 5.

[1] : ![photo_2016-12-25_18-37-13](https://cloud.githubusercontent.com/assets/24765730/21472291/bec1bfe4-cad2-11e6-8591-294755f13c1e.jpg)

[2] : 
![photo_2016-12-25_18-46-20](https://cloud.githubusercontent.com/assets/24765730/21472293/c5f8b20e-cad2-11e6-9386-fb9e9726a765.jpg)

**Comment by kistitan** [comment]
Hi @pappus11,

If you use anonym notifications than all the information is hidden in the notification text so you cannot see by default what is the notification about.
Some of notifications are displayed in the notification history some not.

The reason of why not all of them is displayed is for example because of if you start chatting with someone and you receive a notification for each message your notification history will be full of notifications about your messages, what would make the notification history screen useless.

There are two types of notifications that has their own screen so it does not make sense to display them in the list:
- new message notifications
- new friend request notification

We already have an open story about displaying indicators in the menu so you will see if there is an unread message or friend request is waiting. Until that unfortunately you have to open them to check.

So in you case the notification is not phantom, but you either got a new message or a new friend request.

Please let us know if this is really the case.

Thank you for your patience and understandings.
