### ISSUE TITLE
Cannot start a conversation with someone you're not friends with through the app

### ISSUE THREAD

**Issue by sata** [fetlife/android#303]
I'm using Fetlife App v2.5.8 on Android 7.1.1

Reproduce the issue:

1. click 'Message Kinkster' in Chrome for a user you're not friends with
2. FetLife app opens up with conversations 'page'.
3. From here it's not possible to initiate a conversation with the mentioned user since you're not connected. 

Work around solution so far is opening 'message kinkster' in a new tab, that way you still in Chrome and can initiate the contact.

can someone else reproduce the issue?

**Comment by sata** [comment]
Oh, closing the issue since it's a duplicate of #259

**Comment by kistitan** [comment]
Hi there,

It indeed happens if you select your App as your default for that url.
We removed that option in newer version.

To solve the issue. Can you please go to your device's settings / apps / locate FetLife app and clear defaults?
After this when your device but offers to use the FetLife app or the browser to open the conversation page please make sure you select your browser.

We are sorry for the inconveniences

**Comment by sata** [comment]
Yup, that works! Thank you.

No inconveniences at all!
