### ISSUE TITLE
Upload videos 

### ISSUE THREAD

**Issue by MuckleShiny** [fetlife/android#325]
I upgraded to the latest version yesterday - v2.9.2.
I am now unable to upload videos from my phone plus I can't seem to do it via the Chrome app either. Any ideas?

**Comment by kistitan** [comment]
Hi @MuckleShiny,

If it doesn't work neither from the App but the Chrome it seems to be an encoding issue rather than an app issue.
May I ask if you did try with several videos or you have issues with one or a few specific videos.
Are they specific anyhow? Made by phone or other new device?
Do you get any error message when you try to upload it with Chrome?
Would you mind sharing the video with us in private so we can take a look at it specifically?
If you would not mind you can try to send a link or share it via email to address dreamlite@fetlife.com

Thank you

**Comment by kistitan** [comment]
Hi there,

I close this because of lack of more information.
Please feel free to reopen it if the issue still persist.

Thank you.
