### ISSUE TITLE
Delayed Notifications

### ISSUE THREAD

**Issue by GypsyGem** [fetlife/android#326]
I was browsing the web version of the site earlier today and got notifications of my messages and loves.

Later in the evening, many hours later, I started getting notifications on my Android v.2.9.0 for the same items that I had already viewed and cleared on the web.

**Comment by kistitan** [comment]
Hi @GypsyGem,
Notifications to Android are always sent before the email notifications.
So if you get them earlier it means they got blocked somewhere in the Google eccosystem.
Usually it can happen due to lack of Internet connection or blocked Google push messages (like behind company networks).
Unfortunately once the notifications sent out to Android we cannot revoke then anymore.

**Comment by GypsyGem** [comment]
Thanks for the update!
