### ISSUE TITLE
Two issues ~ probably enhancements 

### ISSUE THREAD

**Issue by Adamselene75** [fetlife/android#329]
The first thing is that, as far as I know, there is no way to delete conversations from within the app. 

The second is that the ability to browse members is not in the app either. Usually one would click "places", and then the name of the city. Even better would be an actual member search sortable by gender, orientation, recent activity, etc.

**Comment by kistitan** [comment]
Hi @Adamselene75 

I am really sorry for the late answer.
Delete conversation from the App is something that we plan to support, there is already an open issue for that.

https://github.com/fetlife/android/issues/298

Member search as it was discussed already a few times it is a tricky question as some users might would not want it so we should be very careful with it.
However as soon as it will be supported by the website we will add to the app too.
Browsing Profiles however is already possible, you can now finds users who are attending an event or appear on your activity feed or just simply friend or follower/follow an other user who you can see.
Places indeed not supported yet, and as of now it is out of the scope due to some planned refactor at the website, bit as soon as anything changed we will get back to this topic.

Thank you for your understandings
