### ISSUE TITLE
Groups: usability

### ISSUE THREAD

**Issue by ghost** [fetlife/android#356]
A few things I noticed that probably shouldn't be:

1. Groups open in Description, not Discussions tab as in the web site. (Especially for groups I'm member of, I'd prefer to jump straight to Discussions.)
1. Discussions open at the last comment, not OP as in the web site. (For long ones it takes a lot of scrolling to get to the OP.)
1. Comments in discussions waste a lot of horizontal space. To the left for avatars and to the right for... nothing. (Given that smartphones are portrait oriented, horizontal space is precious.)

**Comment by flgnl** [comment]
I agree with 1 and 3.
About 2 I am in doubt. Because this works the other way round as well. If a few new comments have been added in a long discussion, I also wouldn't like to have to scroll from the OP to the end again. And as I tend to follow interesting discussions from the start. That would happen a lot more often than the other way round.

My own issues:
4. In the discussion list, the discussions are ordered by the date of the OP. And the date listed is the date of the OP. I'd prefer to have the discussions ordered by the date of the last comment and the date/time listed to be that of the last comment. Just like on the website. Because then I can just see if something new has been added and open that thread. Now I have to open them all to see if something new has been added.
5. If there would be some way to see I I have already read something, like on the website. That would be great as well. By the way, I get the impression that on the website, this is done per brwoser (stored in a cookie?). It would be handier if it was stored in the database like it's done on most fora. That way I can see what's new regardless of the device I'm on. In that case the discussions could just open at the last unread comment. Which fixes the issue of item 2 as well.
6. Links to group posts in the feed still open in a browser. Instead of opening the post in the app.

**Comment by kistitan** [comment]
Hi @Two-Finger, @flgnl 

Thanks a lot for your feedback. We really appreciate any feedback on our new group feature.
About Issues:

1. Totally agree. We were already considering changing the order. We will make sure it will happen in the final version.

2. This indeed a tricky one. We have two different use cases. Users who just browse lot of new discussion without really returning to them and users who use the same discussions again for commenting or reading several times.
As for the first case users still need to scroll only once for every new discussion while users in second uses cases would have to scroll every time they comment (that could be dozens of time per day) we would probably keep the current approach, BUT we will think about how we can support the first use case. For example with a quick icon/link to access the discussion starter right away.

3. This one also makes sense. On the other hand we also think that user indication and give it a chat like layout is also important. But as you pointed out we definitely have some room for improvements. Will work on that too.

4. Yes. We are aware of that. We have right now a technical limitation with the API. We want to improve it but unfortunately it is more difficult that it should be, but we are also thinking about a temporary workaround that can implemented faster to make they order more meaningful.

5. Also very good point, but because higher priority technical issues (like see above), probably it will happen only in the second iteration of the group feature (so not in the first release version) - sorry for that.

6. Yes. Also a thing to be solved! We will do our best to have it soon.


Thanks again for both of you!

**Comment by flgnl** [comment]
1,3 & 6 seem to be solved.

I have a new one.
7. The name of the someone posting something is a the bottom of the post. I don't know everyone's avatar by heart. It would be nice to see who's saying what while reading a discussion without having to scroll down to the bottom of each comment first. So having the name on top would work better in my opinion. And I have been reading quite a lot of group posts in the app the last few days.

**Comment by kistitan** [comment]
Hi @flgnl ,

Thanks for the confirmation about 1,2 and 6 and also for point 7.
We are going to think about an improved design that covers (partly at least) both point 2 and 7.

Thank you

**Comment by flgnl** [comment]
8. Perhaps it is possible to analyse links in posts and if they point to a Fetlife resource available in the app (like another post or an event/user) redirect the link to the resource within the app.
9. Maybe not really usability, but it would be nice if joining and leaving a group would be available within the app.

**Comment by flgnl** [comment]
10. Another idea: on the begin screen of the groups section, a page (similar to search) which shows all new discussions in all groups one is a member of. (Just completely new discussions, not discussions with new comments.)
11. And a follow/unfollow possibile for discussions within the app.

Oh, just for some positive feedback: I'm really happy having the groups functionality in the app. I use it a lot already.

**Comment by mrmucox** [comment]
12. Group notifications send the user to the list of groups, and not the conversion or post referenced in the notification.

**Comment by flgnl** [comment]
13. Visible indicator for closed discussions. As far as I can tell, right now the only way to notice that a discussion is closed is to post a comment and have it show up in red. It would be nice if it was just visible. No comment field and a notification, like on the website for example.
14. And something I just noticed: it would be nice to be able to start a new discussion from the app. This doesn't seem to be possible.

**Comment by flgnl** [comment]
Regarding 4. The new way is somewhat better, although you still have to open a thread and load the comments to get the ordering to change. But I suspect the API issue you mentioned has to do with the datetime of the last comment not being known before the comments are loaded. I can see that would require an API change to fix.

But I also notice that having new discussions without comments doesn't seem to influence the group order. I started two new discussions in my own group just now, but the group is still quite close to the bottom of the groups list.

**Comment by flgnl** [comment]
15. When you have shown more comments by clicking once or more on the dots, and then click on a link, tilt your screen and stuff like that, you can start all over again because only the last comments are visible again. It would be nice if loaded and visible comments stay that way, at least as long as one doesn't go anywhere else within the app.
16. This should be fairly easy to implement: show the name of the group somewhere in the discussion, for example at the top. This may seem superfluous at first, but it isn't. If I open a discussion from a "x commented on a group post" link in my feed, I often have no idea which group I'm looking at.

**Comment by kistitan** [comment]
Hi @flgnl ,

Thank you for the further suggestions.
We release groups as a stable version now, but we will keep improving it also according your comments.
We are also waiting for some server side improvements to do so.

Thank you very much for your help and patience

**Comment by kistitan** [comment]
Several of the original list items have been solved.

Summary of unsolved suggestion:

- See in the App the discussions unread/read at the website: 
Unfortunately it is a browser stored data. Not supported by our database. Still nice suggesstion but unfortunately it won't happen in short term.
Same functionality can be initiated in the App, but that won't be synced for a while...

- Open other resources within the App (pictures, other links)
It is a tough one because of different ids used by the App and the website (for security reasons) but we are working on it.

- Starting new discussion from the App
Good suggestion. On out todo list.

- Indicated closed discussions.
Good suggestion. On out todo list.

- Remember the expanded group posts (with the 3 dots) even if the App is left and returned (to open a link e.g.).
In some cases it already should work. To support other cases is under consideration.

- Show the Group name also in the discussion:
Good suggestion but still under consideration how to add as part of the UI design. Header area is already too small for long title discussions...

All other reported improvements should be solved now.

**Comment by kistitan** [comment]
Hi there,

we are as of now working on it to move all the main screens of the app into webview based screens to have all the features of the website also int he App.
As soon as we get there this issue will be automatically solved.

To avoid extra effort that would cause delay in this progress we most probably not gonna fix these in the native screen.

thank you for your understandings.
