### ISSUE TITLE
No notification

### ISSUE THREAD

**Issue by Bobby-M** [fetlife/android#365]
I'm using the newest version of the app and it does not give me any notifications

**Comment by kistitan** [comment]
Hi @Bobby-M

Thank you for reporting this issue.
May I ask if this is a consistent symptom or something that you realized for a longer period of time.

Due to some recent server side upgrade we notice huge waiting time in notifications occasionally.
This is a high priority issue for us to solve.

Have you received any notification since?

Other then this delay we couldn't reproduce this issue on our test devices.
So if no notification arrive soon to you, would you mind to install a test version of the App with additional logging?

Thank you

**Comment by Bobby-M** [comment]
No I haven't.

**Comment by kistitan** [comment]
Hi @Bobby-M ,

Still could not reproduce or found a reason for this issue.
What you could is to put the app to its default state. 
That could solve if some settings got stuck or so.

You can just go to your device Settings / Apps / FetLife / Storage and Clear all data. 
Than force stop the App.

If it does not help, I will make a new version for extra logging for you tomorrow that could help us to track down the issue.

Thank you for your patience

**Comment by kistitan** [comment]
Would you also mind check if you receive notifications with having the lock screen turned off?

Thank you

**Comment by kistitan** [comment]
Issue still could not be reproduced, does anybody has an update?

**Comment by kistitan** [comment]
Merging to 
https://github.com/fetlife/android/issues/371
