### ISSUE TITLE
Acquiring Updates

### ISSUE THREAD

**Issue by adkins17** [fetlife/android#367]
Every so often, and update is released and I receive the error, unable to connect to server. When I check for an update, it tells me there is a new version availiable. Acquiring that new version in another story. I am no longer getting good auto downloads, and I am not finding a current link to manually download the latest release. Am I missing something here? Is anyone else having these issues when trying to update?

**Comment by kistitan** [comment]
Hi @adkins17 ,

Unfortunately other users also face this issue with auto download.
Mainly with chrome browser. We don't exactly know what the issue is bit it seems to be outside of our reach.
We hope with new browser updates it will work again, in the meanwhile we will make a download link accessible in the App.

Thank you for reporting this issue.

**Comment by kistitan** [comment]
Download link is accessible in the app now via the Android App page.
Hope it will make the install easier.

Thank you
