### ISSUE TITLE
Crashing and Preview

### ISSUE THREAD

**Issue by KenoKracKen** [fetlife/android#368]
Great app. But it crashes, or won't load ALOT. Also the red preview logo NEVER goes away, and I wish it would.

**Comment by navyguyg** [comment]
The "Preview" is there specifically because the app is still in its preview phase, it has yet to be finalized. Hence the constant updates.

**Comment by KenoKracKen** [comment]
My apologies. Thought it was just on my end. Because it was gone at one point. Then in one of the updates it was back again.

**Comment by kistitan** [comment]
Hi @KenoKracKen ,

Thank you for opening this issue.
We are sorry for the confusion. Please let me clarify it.

There are two versions available parallel to the app.
Stable version and Preview version.

If you see the Preview log it means you are using the latest, preview version of the App, that indeed can crash more frequently than the stable version, as it is the first time when the app used under pressure.

By default you get notification about both the new stable and preview versions of the App, because based on earlier feedback most of the users were interested in new features even during public testing.

If you don't mind receiving the most recent features a bit later but would prefer less crashes, you can go the Settings menu item in the App and under notifications turn off the notifications about Preview version.

Please let me know if you needed any more clarification or if you would like to install the last stable version instead of the preview one and needed any help with this.
