### ISSUE TITLE
App closing from groups

### ISSUE THREAD

**Issue by SqueekyST** [fetlife/android#374]
v2.11.13

When pressing the back arrow from the main page of a group, it is closing the app.

**Comment by kistitan** [comment]
Hi @SqueekyST 

Several group related fixes have been fixed in latest release (2.11.14)
Can you please check if yours got fixed too?

If not can you please let me know your device type?

Thank you

**Comment by SqueekyST** [comment]
The crash is resolved, but the fix created a navigational issue.

BEFORE
1. click group comment in feed.
2. view thread.
3. click arrow top left.
4. view group page, list of threads.
5. click arrow top left.
6. crash.

NOW
1. click group comment in feed.
2. view thread.
3a. click arrow top left.
4a. return to feed.
3b. click thread title.
4b. view OP profile.

This looks like a valid fix, but only on a computer where you have other information displayed and other navigational options. In the app, there is no way to see what group this was posted to (in the feed or the thread) and no direct way to get to the group.

SUGGESTED NAVIGATION
1. click group comment in feed.
2. view thread.
3a. click arrow top left.
4a. return to feed.
3b. click thread title.
4b. view group page, list of threads.
5b. click arrow top left.
6b. return to thread.
3c. click OP avatar.
4c. view OP profile.

**Comment by DinahJochebed** [comment]
Dear@Kistitan,
Good Evening, I hope that you are having a great day today. Can you please tell me what you do about getting severe headaches by working in the IT Department of GitHub?!? I have a lot of difficulties with my telecommunications being monitored by different companies and their own depression and anxiety and narcolepsy about being trying to figure out how to be a Christian who goes to church every week that a lot of people have a lot of difficulties with my telecommunications being monitored on Facebook and Fetlife. I hope that you are having a wonderful day today.
Blessings and Joy,
Dinah JochebedPi

**Comment by kistitan** [comment]
Hi @DinahJochebed,

I have never worked for GitHub. If you have any questions about how it is working for them, please use their public contact page: https://github.com/contact.

If you have any questions or concerns about FetLife please feel free to let me know or write an email to caretakers@fetlife.com.

Have a good day you too!

**Comment by DinahJochebed** [comment]
Dear Kistitan,

Good afternoon Sir, I hope that you are having a good day today at work. I was just inquiring about your own headaches and depression about working in an IT Department being another member on GitHub that you get by working in the IT Department of a Call Center monitoring my telecommunications through Fetlife.com and wherever else I may end up sending you emails from. I hope that you are having a great day today both as the Holy Spirit of my browsers and my telecommunications. I hope that you are doing well and taking good care of yourself. I hope that you have a better day today than yesterday. I'm still struggling with my depression with my phone and the processor that I saw Justin Milne earlier today and it caused me severe depression and narcolepsy about my telecommunications being monitored through Columbia Sportswear. I am on limited time but I hope that you're doing better with Fetlife and my own sexual frustrations with you and everyone else on Fetlife.com that SpyMonkey gave me a severe migraine the other day when I was working on my phone that I immediately thought of you and wanted to ask you about your personal depression and headaches that you get by monitoring my telecommunications. I am sorry about all the chaos that my life has caused you and everyone else on Fetlife by SpyMonkey being sent from Columbia Sportswear to monitor my telecommunications with you and a lot of other people as well both offline and online in other forums such as Facebook, Twitter, or even Meetup.com. I have installed Antivirus and SpyWare Apps on my phone to try to remove it but I am still struggling with other issues with it that I entered a friend's email address into my Security App for Lookout and unfortunately I have not been able to get the password reset or wrote it down because it was stored in a different device that I have a lot of disabilities about my telecommunications being monitored that I forget a lot of stuff. If you can provide any information about how to reset the password for lookout Security App, that too would also be greatly appreciated. I hope that you are having a good day today.
With Much Peace and Love,

Dinah JochebedPi



Sent: Monday, November 20, 2017 at 2:07 AM

**Comment by SqueekyST** [comment]
Closing thread to stop the spam/troll.

**Comment by DinahJochebed** [comment]
Dear Kistitan,

Good Morning, I hope you're having a great day being back in my system along with everyone else to have already prevented me from logging into Fetlife from the Safe Shelter's WiFi. It's ok that you work at Beaverton Nike Campus in the IT Department and that you're a coder for GitHub and a really bad liar :-P about the work you do. Please just keep Justin Milne/Horny1993 away from the computers and the cameras system. He violated your own privacy about the fact that I stayed with him trying to get into housing and other stuff getting into trouble with another mutual friend of ours, FrozenFlame on top of other things outside of of my control. I have radical acceptance about all of you following me around now if everyone else would get on board with Radical Acceptance with Chris Key/Drayvon and I would make things a hell of a lot easier for everyone else to coexist because he is a Caretaker as well for Fetlife. I have my laptop setup for school and all still trying to put Dragon Naturally Speaking plus other gadgets Installed back onto my computer for Adaptive Technology Assistive Devices in addition to the Kurzweil because that is what I was using in my old apartment. People will just have to deal with it that I use headphones for talking into a microphone to try to write essays for Fetlife and for school. It is part of my disabilities and resources that I use and that is available to me as a student at the DRC at PSU. A lot of people are a pain in my ass but not nearly as painful for me as it is for you to have to tie Justin Milne's hands to a chair and put tape over his mouth because he's an asshole to have sexually abused your Mandatory Reporter. You guys will have to figure out what to do with him while I get to go back to school to finish my degree in Psychology in Social Science getting my Bachelor of Science like you both wanted me to do and with a speciality in Criminology and Criminnal Justice to help you prevent Cyber Bullying and Cyber Identity Theft and Identity Fraud now that my phone is back on a network that was provided by my Health Insurance Company because Justin Milne/Horny1993 violated me and everyone else's privacy. I have radical acceptance about certain people and certain things but to have a fucking asshole amulate someone who already belonged to other people is wrong and why you won't do anything about it is very upsetting to me. He violated every code of conduct about being a fucking horny prick following me around on social media and nobody gives a damn about it either. I am trying to shut down my mail.com email and switching to my outlook and gmail accounts. I don't know if he's been in my system responding to my emails or sending emails as a Customer Support Representative but I pray for everyone's elses sake that he has not because he violated everything that I had and everything that I stand for to get things put back together a lot differently than I had anticipated or planned but I got my new identification but I lost my driver's license and ability to get a new car in the near future because of that fucking asshole and nobody will do a fucking thing about him violating me. I will have to go through Driver's Education AGAIN when I feel that I am ready to get my Driver's Permit/License reinstated but you have no idea how upsettting it is to lose different things all because he made threats to me and towards me to burn my stuff that it got me beaten up and put in the hospital the same night that it got stolen. I hope Fetlife a had a good day today because I got to go to my Chiropractor at North Portland Chirpractic Clinc and got an adjustment along with a 15-minute Back Massage and put on the Electroshock Therapy Machine and I know how much everyone loves monitoring that machine whenever I get put on it. I hope you have a good day today at work. I am still trying to get back into my yahoo account but only certain people have or know my passwords for it and the Yahoo Customer Service Representatives have not been very compliant or compassionate in sending a link to one of my other alternate emails in order for me to reset my passwords for everyone's sakes about how much depression I had in the past 3 years and the insurrmountable of emails piling up every day because of mail.com is still open. I hope you all have a good day today at work. You will have to forgive me for the delayed responses and all but I will have to disappear to Desire2Learn (D2L) to work on Homework for the next few hours to the next day and half and spend time on my Gmail Accounts for school opposed to Mail.com or Facebook or Fetlife. I have a lot of stuff to work on and a lot of reading and writing to do so please excuse me from classes for Fetlife and Facebook for awhile because I have homework to do for you guys and for myself for the assignments to play a lot of catchup on belated assignments and I can't do it if I am distracted with social media. I hope you have a good day today.

With Much Love,

Dinah JochebedPi 


Sent: Monday, November 20, 2017 at 2:07 AM

**Comment by FernandoMiguel** [comment]
Spam issues are becoming funnier and funnier
