### ISSUE TITLE
Request: Making full profiles viewable in app

### ISSUE THREAD

**Issue by ImperfMage** [fetlife/android#403]
Hello I was wondering if there has been any thought of making full profiles viewable in the app, instead of the just the basic info and the bio (which I may add the styling seems to not work in there) and having to click "view profile"

**Comment by kistitan** [comment]
Hi @ImperfMage,

Most of the information is accessible also via the App.
May I ask what information you miss the most?

Thank you for you help

**Comment by ImperfMage** [comment]
Like say if I wanted to view someone's photos or fetishes , or see what groups they are in

**Comment by kistitan** [comment]
Hi @ImperfMage again.

Yes, that's why was I confused. Because most of these are possible in the App.
In the app you can just slide to the right and left to select what part of the profile you would like to see.

Photos and groups are available.
Fetishes might take a bit longer as it is under design.

**Comment by kistitan** [comment]
Closing this issue, as the requested information is available.
Note: design should be imporvemed to make it clear, but there is an open issue for that already
