### ISSUE TITLE
Put App icon on the home screen after installation

### ISSUE THREAD

**Issue by jidanni** [fetlife/android#405]
Remember to put an app icon on the home screen after installation. Or somewhere in settings say that the lack of an app icon on the home screen is on purpose and touch here to add it.

**Comment by FernandoMiguel** [comment]
Afaik adding a launcher icon is a system wide setting, not a per app option

**Comment by kistitan** [comment]
Hi @jidanni ,

Thanks for your message.
In theory we could make an app without launcher icon but for that we should make sure we do not have any launcher activity.
FetLife App has a launcher activity so App icon should be paste after installation.
We do not have any more influence on this

**Comment by jidanni** [comment]
All I know is on Android 7.0:

If I install some app from the Play Store, an icon appears on the home screen.
I can touch this icon to launch the app.


If I install the Fetlife .apk, no icon appears on the home screen. If I
want to use the app, I must dig it out of "all apps".

**Comment by ironjan** [comment]
@jidanni This behaviour depends on the phone respectively the app launcher (e.g. NovaLauncher instead of the default) you are using. Adding to the homescreen may be disabled for "non Play Store"-apps.

You can add the icon to the homescreen by dragging it from the app list to the homescreen (just press and hold the icon in the list).

@kistitan What the first comment seems to suggest is a function like "[Add shortcut to home screen](https://stackoverflow.com/questions/4854197/how-can-i-place-app-icon-on-launcher-home-screen)" in the app settings.

**Comment by jidanni** [comment]
OK. @ironjan Maybe mention that in the FAQ at the bottom of https://fetlife.com/android : "I installed the app OK, but now I can't find it".

**Comment by FernandoMiguel** [comment]
which phone and launcher is that?
most users know how to pull the launcher up and find their apps there.

some ROMs dont have a deck, and mimic iOS with all apps in the desktop

**Comment by jidanni** [comment]
@FernandoMiguel Stock [Asus ZE552KL](https://www.asus.com/zentalk/thread-192045-1-1.html) Android 7.0 phone and apps.
