### ISSUE TITLE
Add Preference to always use external browser

### ISSUE THREAD

**Issue by jidanni** [fetlife/android#408]
Some items open in an internal browser.
But there should also be a Preference choice added to always open such items in an external browser,
even if one can do that when one pleases via the internal browser's menu.

**Comment by kistitan** [comment]
Hi @jidanni ,

I am not sure if I understand what do you mean.
What do you mean under internal browser?

Thanks

**Comment by jidanni** [comment]
https://www.addthis.com/blog/2017/04/04/in-app-browsers-explained/
http://www.androidpolice.com/2016/07/20/google-explains-chrome-will-become-webview-android-7-0/
Like https://www.google.com/search?q=always+open+links+in+external+browser&tbm=isch

**Comment by kistitan** [comment]
Hi @jidanni,

Thanks for the links, but I meant what parts so you experience as internal browsers within the FetLife App :)
Because we indeed use webviews to display some web content that are close to be identical with the web page but not the same.

So they rather can be called as hybrid views than browser views.
The reason why we are planning to keep those pages like that is the seemless integration with the other App.
Like if we open a FetLife web content that would not make sense to reimplement, we still want to handle the links from the page and open the in app pages. 
If we open them in external browsers you can never get back to the App.
Also the App response time is better this way.
But obviously I am referring only for FetLife internal pages 

The internal browsers solution that you refer above are about external links that some App indeed can open internally (like opening a link to Disney website from Facebook post).
We don't do that in FetLife App.
Every external links is opened in external browser.
