### ISSUE TITLE
In-App Onboarding

### ISSUE THREAD

**Issue by Daddy** [fetlife/android#418]
Onboarding, arguably is one of the most important aspects of a service and especially its application as it's the first UX that a member will experience when joining and [statistically can make or break user-retention](https://www.shopify.com/partners/blog/mobile-app-onboarding).

Many apps allow for users to complete the onboarding process completely through the app, which not only improves user-retention, but also makes the entire experience far more streamline. Currently, to both sign up as well as reset your password, you have to leave the app and visit the FetLife website.

This may differ somewhat (I'm sure you can tell internally) for the FetLife community as most of the app's downloads may be from those already apart of the community. In which case the priority of this should be lowered.

**Comment by kistitan** [comment]
Hi @Daddy ,

This is definitely an interesting suggestion that we should take into consideration.
Without having final opinion, what comes into my mind is that the implementation would be relatively complex, and it is hard to judge how many users would it actually target.
I would say it indeed would be nice, but maybe has a bit lower priority than some missing features (like comments) within the App.

**Comment by kistitan** [comment]
This feature will be part of the app as a side effect of the new App concept, using webview based screens instead of native ones.
Login screen is one of the top items in our todo list, so it sould happen in short term.

As we have separate issue tracker for that progress, please allow me to close this one, as this feature won't be implemented for the current native screen.
