### ISSUE TITLE
Login Design Improvements

### ISSUE THREAD

**Issue by Daddy** [fetlife/android#419]
![image](https://user-images.githubusercontent.com/19200290/35012051-332693d0-fabd-11e7-9119-a82f5bab7ccf.png)

I suggest the following improvements to the login page to provide a better experience for the app's members in addition to accessibility concerns. Each point aforementioned will be expanded upon below.

**Replace the word "FetLife" with the FetLife logo**
This provides a cleaner design, reduces the amount of white-space (or in this case grey-space?) at the top of the login window, contrasts better with the rest of the page, and removes an unnecessary mention of FetLife.

**Addition padding/margin between footer links**
For members with larger fingers or otherwise other accessibility concerns, clicking into the correct option can be rather difficult and result in the wrong action on occasion. Adding even a 3-10 pixels of padding or margin would improve upon this.

**Improper padding on the Remember Me form option**
This is the smallest detail and nitpicking, but the padding should be corrected to be identical both above and below the checkbox and it's label.

**Comment by kistitan** [comment]
Hi @Daddy ,

Thanks for the suggestions.
We will take a look at them.

**Comment by kistitan** [comment]
This feature will be part of the app as a side effect of the new App concept, using webview based screens instead of native ones.
Login screen is one of the top items in our todo list, so it sould happen in short term.

As we have separate issue tracker for that progress, please allow me to close this one, as this feature won't be implemented for the current native screen.
