### ISSUE TITLE
Installation not smooth if need to toggle unknown sources in settings

### ISSUE THREAD

**Issue by jidanni** [fetlife/android#421]
A big problem in the upgrading sequence
is if the user needs to turn on allowing unknown package sources in settings of his phone. By the time he returns from that sequence the whole package installation process is lost, and he needs to dig up again the. APK file from his downloads directory there on his cell phone.

Of course we should normally keep this turned off for security and we only turn it on to install the FetLife app.
So maybe the installation script should detect that he needs to turn on the unknown sources and then help him go there. And then when he comes back using the back button then the installation process should continue. In fact when the installation process is completely over just for fun you can even take him back to settings where he can turn back off his unknown sources item.

**Comment by kistitan** [comment]
Hi @jidanni,

We are aware of that problem, that does exist in some devices, that's why we have the installation trouble shooting guide.
Unfortunately that part of the installation and upgrade process is out of our hands as it is part of the Android OS itself.
It usually works well, but indeed on some devices on stood as you write and you need to start it again manualy.

We hope it will be solved on more and more devices.
