### ISSUE TITLE
Android 5.1.1 unable to update past app version 2.13.2

### ISSUE THREAD

**Issue by CyBradMachina** [fetlife/android#422]
Unable to install past 2.13.2 unfortunately would like to get 2.14.0 forward :/

**Comment by kistitan** [comment]
@CyBradMachina 

What is the issue that you actually face?
Do you have issues with downloading the upgrade?
Or do you manage to download it, juts it does not install? At which step does it stop?

**Comment by CyBradMachina** [comment]
It won't let me install it. It downloads just fine but the actual installation won't happen try as i might the install button is grayed out

**Comment by CyBradMachina** [comment]
If I'd meant it wouldn't download i would have said it wouldn't download I don't need specific hand holding I'm pretty tech savvy though I'm not a coder so when i say something there's specific reasons I'm using those specific terms just saying and i realize you're used to dealing with people on here with kid gloves that don't know a string of code from a hole in the ground and not saying I'm a master guru of tech neither just saying i do know what basic terms mean and try to use them as accurately as possible most times but anyhow

**Comment by CyBradMachina** [comment]
Also as a further investigation on my end on a different phone with Android version 4.1.2 also won't further update  (downloads but the APK doesn't install and crashes the installation) past v2.12.22 and uninstalling will most likely result in being unable to reinstall at all but that's just speculation

**Comment by kistitan** [comment]
Hi @CyBradMachina ,

Thank you for clarifying your background, I am sorry if previous question was bothering for you. 
We have several users with different background and it turned out several times that for some users the whole process of upgrade is one flow, they did not even recognized an actual file was downloaded in their file system. That's why the question.

This is a pretty unfortunate and unique situation. The installation process is out of our hand as it is guided by the Android OS, and without getting any error description we are in a bit of a dark.
What can we confirm that in theory apk should be fine as many users managed to install on their phone and also several who were upgrading from version v2.12.22 from lower.

So I am sorry, but as of now we also cannot do much more, but brainstorming on what could possibly go wrong and indeed we might can come up with something that you have already tested, or it is evident for you. Sorry for that.

As a next idea, may I ask if you use different profiles on your phone? Like a guest profile?
Sometimes it can happen that an App is installed only on one of the profiles, that can cause some issues.
I am also wondering if you still have the last APK file that you installed and where the installation worked. And also the one that you are using now.
If you could send me those to dreamlite@fetlife.com, we could check if the files are indeed correct.

Thanks

**Comment by CyBradMachina** [comment]
No multiple profiles that I'm aware of and yes my apologies i sorta snapped at you was having an off day that day unfortunately 🙁 and as for old APK file it's probably long gone by now and i can get the new one but it'll be the same one automatically available

As a side note i also have a half broken s7 with Android 7.0 (it may be a bit higher) and the updates worked just fine no issues so I'm wondering if it's older Android OS incompatibilities rather than the app itself if you see what I'm saying?

**Comment by CyBradMachina** [comment]
Tried resetting all app preferences thinking maybe I'd set something to default specifically an app to run with APKs but still no dice and it basically stalls as i still can't progress past the cancel or install (greyed out) screen

**Comment by kistitan** [comment]
Hi @CyBradMachina,

This is getting more weird. Our minimum OS version is set to Ice Cream Sandwich so it should not be the issue in theory.
Finally I also managed to get a device with 5.1.1 and the App got installed without any issues.

I don't know how much more effort would you like to put in it, but what certainly could help if you try to install the APK from your computer using Android Device Bridge.

Here is an article about how to set it up:

https://www.google.hu/amp/s/www.xda-developers.com/install-adb-windows-macos-linux/amp/

At one point at the tutorial there is command mentioned "adb devices" if you at that point use also command "adb install [path to the APK file] than it will install the APK OR at least it will give some meaningful reason why it doesn't install.

**Comment by CyBradMachina** [comment]
Alright will try that ty

**Comment by CyBradMachina** [comment]
Tried to create an adb and it was hanging and locking up even when i could make the connection it hung and hasn't made a connection since unfortunately

**Comment by kistitan** [comment]
Hi @CyBradMachina ,

I am sorry it did not work out, but I have to say the issue seems to be out of our reach and we also out of ideas  here :(
Please let us know if we can help you out in any other way.
