### ISSUE TITLE
App enhancement requests

### ISSUE THREAD

**Issue by dacsdd** [fetlife/android#431]
And few things I've noticed that the app desperately needs are: 

1. A way to comment on pics, walls, etc. 

2. A way to view fetishes and add or remove them. 

3. A way to edit your profile, add writings and wall posts 

4. A way to search by area. (Search function doesn't allow for anything other than exact name) 

Thank you for your attention in these areas.

**Comment by kistitan** [comment]
Hi @dacsdd ,

Thank you for opening this issues.
Indeed all these you mentioned are valid points and they are on our todo list to support somewhere in the near/mid future.

**Comment by kistitan** [comment]
Hi there,

As of now we are working on a new App conept using webview based screens instead of native ones.
That solution will make all the website features available in the App.

As we have separate issue tracker for that progress, please let me close this now, as these won't be implemented for the current native screens but rather the whole content will be replaces.

We hope it will happen in short/mid term
