### ISSUE TITLE
Cropped status 

### ISSUE THREAD

**Issue by FernandoMiguel** [fetlife/android#435]
![screenshot_20180224-085627](https://user-images.githubusercontent.com/168366/36627922-fa97b762-1941-11e8-8333-18fff44655cf.png)
Weirdly this status post by @johnbaku was cropped

**Comment by kistitan** [comment]
This is actually works as designed.
In the feed list we only display a preview and long texts are not fully displayed, otherwise the whole feed could end up in endless scrolling.

But I agreed it is also not nice this way. There should be an indication that it is not the full text and you should click on it to read the full text.

**Comment by kistitan** [comment]
This issue will be automatically fixed with the new App concept, having webview based screens instead of native ones.

This hopefully will happen in short/mid term.

As we have a separate issue tracker for that progress, let me close this issue now, as it won't be changed in the native screen.
