### ISSUE TITLE
Issue with notifications?

### ISSUE THREAD

**Issue by Lilchik2086** [fetlife/android#436]
I've seen a few messages about people having issues with notifications, but they seem to be a bit old, so I would like to in for y'all that the most recent update isn't giving notifications on anything, conversations, photos liked, friend requests, nothing.   Haven't had a notification from get on my phone in over a week.

**Comment by kistitan** [comment]
Hi @Lilchik2086,

First of all I apologise for the late reply.
We didn't notice any reason for having notifications down from server side recently.

Would you mind double checking if your "web notifications" are allowed in your FetLife webpage settings? It must be on in order to receive notification in the App.

**Comment by WitcheyOne** [comment]
I am also having this issue. My web notifications are on.

**Comment by kistitan** [comment]
@WitcheyOne 
May I ask if it is continious issue or periodical?

**Comment by WitcheyOne** [comment]
Continued. I don't see the notifications in the app... It'll take me to the
section where I'm supposed to see them but it's always blank for me.

**Comment by kistitan** [comment]
With current version now both in App and generla notifications are accessible so the list should be full.
Closing this issue now...
