### ISSUE TITLE
Improve profile screen with adding tabs instead of swiper

### ISSUE THREAD

**Issue by troybarrytoo** [fetlife/android#442]
for those new to the app, the swipe navigation bar (red w white text) appears to be a button  bar with one button far right, title centered.

'tabs' would be more tradition, showing all options, vs swiping through all options to get to the last option.

if not 'tabs', adding an arrow icon to the right of the far right 'navigation bar' label would visually indicate that the label is not a button.

not a bug obviously, but an improvement in usability.

**Comment by kistitan** [comment]
Hi @troybarrytoo 

We got this feedback several time, so thank you also opening a Github issue for it.
When the App started to implement it was a relatively common native UI element. 
In the meanwhile it is not really used anymore most probably because of the issues you mentioned.

We should revise the current solution and replace probably with a slidable tab bar, but please give us some time to figure out the best improvement.

**Comment by kistitan** [comment]
With our current App concept, we are going to replace native screens with webview based ones, so as soon as responsive profile screen is available this issue will be solved, however as it might take some time, I keep this open as we should consider fixing this even for the native screen.

**Comment by nielsenramon** [comment]
Closing this in favor of a new profile page that is incoming.
