### ISSUE TITLE
App notifications

### ISSUE THREAD

**Issue by IAmAdulting** [fetlife/android#450]
2 or 3 versions I used to get app notifications but that stop with the last version. Is that an option with this version?

**Comment by kistitan** [comment]
Hi @IAmAdulting ,

There were not code changing in connection with notifications. 
May I ask if you still do not receive notifications?
There might be some temporary delay in the infrastructure, but otherwise it should work.

Would you mind also checking your settings at the website if web notifications are allowed and if also in the App's settings if notification setting is on?

Thank you

**Comment by kistitan** [comment]
We found some possible issues that might cause some notification losses on certain OS versions. 
these have been fixed, and we do not see any further possible reasons other than the general architecture based reasons (low connectivity, internet outage, etc).

Closing this issue for now, please let us know if notifications still get lost repeatedly, with stable connection.
