### ISSUE TITLE
v2.16 broke group notifications 

### ISSUE THREAD

**Issue by FernandoMiguel** [fetlife/android#461]
Combined with another ticket that does not expand notifications,
On v2.16 it's impossible to see the group notifications that you follow as it was before

**Comment by kistitan** [comment]
@johnbaku @reneklacan 
Can you please help me out with this?
In the in-app notification screen we displayed incoming group notifiations (new mentions, messages, etc), is that so that in the website version these are not visible?

Thank you

**Comment by FernandoMiguel** [comment]
In the site we can view that activity in the Group tab.
I really liked the way we did it before in the mobile app. 
Besides checking my feed, the notification tab was my second most used part of it, to keep with group posts I'm subscribed to. 
Now I can't do that from the app. 
It's an huge loss of functionality

**Comment by kistitan** [comment]
@FernandoMiguel ,

It is at the moment a theoretical question:
What would you think about a temporary solution where in the settings screen you can use a checkbox to turn back the old notification screen instead of the webview version, at least until our group page support the same functionality?

@johnbaku 
What would you think about this temporary solution?

**Comment by FernandoMiguel** [comment]
@kistitan anything that gives me the same set of functionality I had before...
right now i get multiple notifications and I cant see what they are for

thanks

**Comment by johnbaku** [comment]
@FernandoMiguel I appreciate your frustration. If I relied on that feature I would be annoyed if someone took that away from me as well.

> What would you think about a temporary solution where in the settings screen you can use a checkbox to turn back the old notification screen instead of the webview version, at least until our group page support the same functionality?

I am not a fan of that solution because it's out of sight, out of mind, and the chance we will find a long-term fix to that is greatly reduced.

Instead, can we add back the old Notifications just under a different name? What would be the most logical name for it?

<img width="698" alt="android_app_board_ _figma" src="https://user-images.githubusercontent.com/22100/42766924-86d90c8c-88d0-11e8-83f0-6b72b6c23a87.png">

How does that sound?

**Comment by FernandoMiguel** [comment]
Hi @johnbaku
I don't mind any implementation, really.
You know how the website has its own group tab with subscribed threads? 
Should we mimic that on the mobile app? 
Sounds like the right approach

**Comment by kistitan** [comment]
App notification has been added. Closing this.
