### ISSUE TITLE
Fullscreen picture browsing limit

### ISSUE THREAD

**Issue by tcdfl** [fetlife/android#467]
When browsing fullscreen pictures only ~24 images can be scrolled thru at a time.  After that you have to go back to grid view scroll down to load the next set then go back to fullscreen mode.

**Comment by kistitan** [comment]
hi @tcdfl 

It is unfortunately works as designed. The image swipe display as many images as many you have in your list. The swipe is an external libary that has no paging mechanism.

We already have an issue for that to improve it in the future but it is a complex work so I cannot give you estimate when it is going to happen.

Thank you for your understandings.

(clsoing due to duplication)

**Comment by johnbaku** [comment]
@kistitan mind linking to the duplicate issue just so we have traceability? Thanks.

**Comment by FernandoMiguel** [comment]
@johnbaku https://github.com/fetlife/android/issues/434
