### ISSUE TITLE
No notifications on Fire HD

### ISSUE THREAD

**Issue by TadeoNYC** [fetlife/android#474]
I don't know how many others use Fire tablets, so this may not be a priority. Depending on the difference in framework it may be be a big overhaul. I've side loaded dolphin, which is not without issues as well.

I do get notifications when new versions of the app are available, but that is all.

**Comment by TadeoNYC** [comment]
My apologies for delay as well. I can see the notifications in the normal notifications menu, but app notifications only list new updates.

I have all of the exact same settings as on my Galaxy S7, which works as it should, except now with latest preview, but that's not for here 

Incidentally, the text on the settings page is greyed, but clickable, and submenus appear normal.

I just installed Firefox, in addition to Dolphin and Silk, which i already had installed. I thought perhaps that might help with the framework, but app notifications haven't changed.

**Comment by kistitan** [comment]
Hi @TadeoNYC ,

App notifications screen unfortunately works a bit unreliable. 
It shows only those push notifications that actually reached your phone, since last clear/install.
It is also one of the reasons we are going to have the new webview based screens to make sure you will have the exact same information available via the website and the app.

App notifications is still kept in the App temporarily to at least support those notifications that arrive to the phone, and not covered by the webview based notifications screen.
As soon as we have the full coverage we will no longer need it.

we are sorry for the inconveniences. 

Note: There is an open issue for hardly visible Settings screen, the reason is that some devices override the theme of pre-generated settings screen, what makes it hardly visible.
We did not find a solution yet, that covers all the device types. We are sorry about that.

**Comment by kistitan** [comment]
Hi there,

I am closing this issue now as we introduced webview based notifications screen that should be consistent with the website.

thank you
