### ISSUE TITLE
Can not add comment

### ISSUE THREAD

**Issue by Keen-man** [fetlife/android#477]
Hi
If someone from my friends love some image and I show it to (by clicking), I can not show any comments under image and can not type any comments.
When I slide by finger to top, showed image is cancelled and fetlife app show me homepage (feeds). Can you change it to show comments under image instead of go to homepage?
Sorry for my English. I hope you understand my point.

**Comment by FernandoMiguel** [comment]
the app doesnt have much of writting components, except for the Groups.
for status or image comments you need to open the website.
you can click on the View button on the right side

**Comment by kistitan** [comment]
@Keen-man 

Sorry for coming back to you that late.
It is indeed one of our biggest missing feature in the App.

3.0 was an experimental native work, where you indeed could leave comments, however as in the meanwhile the comment interface in the website is being improved it would be anyway get obsolote soon. 
So what we are working on at the moment is to have a webview based version that guarantees to have the same feature set both in the app and on the website.

Thank you for your patience and understandings

**Comment by kistitan** [comment]
We are working on a different App concept having the screens webview based instead of native ones, that will make all the website features, including adding comments, available.

Hopefully this will happen in short/mid term.

As we have separate issue tracker for this progress, please let me close this issue, as it won't be added to our current native screens.

Thank you.
