### ISSUE TITLE
fetlife ios

### ISSUE THREAD

**Issue by LittleRedWolfess** [fetlife/android#493]
hello! i am one of a few that has iphone and unlike other people that i know that have andriod, i am not able to know exactly when i receive notifications and its kind of upsetting not being able to and replying back to others takes longer then it should i was wondering if somewhere in the near future it will be available for iphone as well

**Comment by kistitan** [comment]
@LittleRedWolfess 

We had an experimental work for iOS and some enthusiastic users time to time work on it, but as it cannot be published to the App store due to its policy even this experimental work is accessible only with some developer knowledge.

We continiously seek the opportunity to somehow have an iOS app easily available for the users, and if we will be able to figure out something we will announce it at the website. 
In the meantime we work hard on making the website responsive and easier to use from any mobile device.

Thanks for you patience and understandings.
