### ISSUE TITLE
Where is the api documented?

### ISSUE THREAD

**Issue by agathe-vault** [fetlife/android#501]
Everything is in the question. I searched in the website but i couldn't found it. I would like to help for the development of this app but i would like to know how does this api work so i could really help...

Thx a lot for your help

**Comment by agathe-vault** [comment]
Yes I saw it. But how did he know such endpoint exist? I think many are missing because I can't find endpoints for fetishes for exemple. Without this information i can't implement missing features...

**Comment by kistitan** [comment]
@agathe-vault 

Thanks for your question.
Unfortunately it is true, we do not have official API documentation, however you can take a look at our FetLife API class where we use almost all of the existing endpoints.

https://github.com/fetlife/android/blob/master/FetLife/fetlife/src/main/java/com/bitlove/fetlife/model/api/FetLifeApi.java

Android App is missing several features also because there are no endpoints to support them

Please keep in mind that with our current concept we are going to replace native screens with webviews and the most of API endpoints won't be supported anymore after that.

Thanks for your understandings.
