### ISSUE TITLE
Version 2.23.0 Issue(s) with some "Menu" links rendering blank/black screens

### ISSUE THREAD

**Issue by Stryker1952** [fetlife/android#532]
After installing version 2.23.0 the following "Menu" links render a blank/black screen and fail to display the anticipated page.
K&P
F&P
Stuff you Love
Groups
Events
Places
App Notifications

While on the blank/black screen no app icons are viewable at the bottom of the App.
A back arrow while on the blank/black screen results in the app minimizing.
Upon restoring the app it returns to the "Start Screen".
Occasionally when selecting one of the links above the screen will flash the wallpaper and then render the black/blank screen.
It almost appears as if the target page is rendering but then being over written as blank.
It acts like a video render issue but that is just a guess.

I have a Pixel 2 XL and I am running "Pie" with the latest security patches.

This issue was not present in 2.22.0
If I reinstall 2.22.0; by first uninstalling 2.23.0; the all functionality returns to normal.
Note: I can not reinstall 2.22.0 over 2.23.0 I must uninstall 2.23.0; I assume that is "by design"

If you have further questions drop me an email and I'll come back here and respond.
Good Luck!

**Comment by ntysecrets** [comment]
Experiencing same issues in addition to app doesn't stay logged in.  Had to go back to 2.22.0

LG G6 Android 8

**Comment by adkins17** [comment]
Having the same issue, I can't seem to load the list of changes made for 2.23.0 with out the screen going grey, locking up, and crashing.

**Comment by kistitan** [comment]
Hey guys,

thanks a lot for letting us know about these issues.
We got several reports about these, but as we weirdly cannot reproduce them, we cannot find a reason behind the issue.

If any of you have some time and energy would you mind helping us out with installing a version with extra debug logs.

In order to do so, please: 

- download the attached zip file
- rename the .zip to .apk
- install the .apk file on your device
- start the FetLife App
- reproduce the issue a few times
- than go to your FetLife App's menu
- Click on Share Logs
- Send us an email to krisztian@fetlife.com 

[fetlife-2.23.1.zip](https://github.com/fetlife/android/files/3023798/fetlife-2.23.1.zip)

Thanks a lot

**Comment by kistitan** [comment]
Merging into: https://github.com/fetlife/android/issues/529
Having the same source of issues
