### ISSUE TITLE
Log out after upload

### ISSUE THREAD

**Issue by SqueekyST** [fetlife/android#536]
Every time I upload a photo from the app it logs me out and takes me to the login page.

I have checked for updates. I'm using the most recent version.  
ASUS_XO18D (Asus update available but not compatible with my service provider) 
android 7.0

**Comment by FernandoMiguel** [comment]
I can confirm this has happened to me yesterday too.
Never happened before

**Comment by kistitan** [comment]
Hi @SqueekyST, @FernandoMiguel 

Sorry for coming back to you with delay.
I have responded earlier, but appearantly did not submit the reply. 
Sorry for it.

Thanks to you we found the issue and it is fixed in 2.23.14.

Please feel free to reopen this issue it it happened again in the new version.

Thanks again for your help and patience
