### ISSUE TITLE
No Share button in conversations in v3.0.0

### ISSUE THREAD

**Issue by Ezra** [fetlife/android#541]
# 🐛Bug Report

### Bug description 

I just updated the app to v3.0.0-beta.1 on my Samsung Galaxy S8. The Share button has now vanished from my conversations. As far as I can tell this means I can no longer send photos in any way, or use my Share List in any way beyond adding to it.

### Steps to reproduce

1. Install v3.0.0-beta.1
2. Go into a conversation, e.g. via Inbox > some conversation
3. Check around the text entry and "Say It!" button; observe no Share button.
4. Scroll through the rest of the page; observe no Share button.

### Expected behavior

In e.g. v2.22.0, there is a Share button next to the (much more compact) text entry area. This button allows sending pictures from the Share List, as well as recently viewed pictures. As far as I know this is the only way to send pictures through the app.

### Screenshots

My screenshots aren't sensitive but I don't see any way to upload an image here, so I'm gonna go ahead and send them to krisztian@fetlife.com.

I'm sending screenshots of both ends of a test conversation between myself and my partner, with his permission. Our devices are both Samsung Galaxy S8 with Android 9; mine is running FetLife v3.0.0-beta.1, whereas his is still v2.22.0.

### Environment

 - Device: Samsung Galaxy S8
 - OS version: Android 9
 - App version: v3.0.0-beta.1

### Additional information

Checking the web interface this does seem to be "the same design and feature set as the website". But it's also a serious feature regression - is it really intended?

**Comment by kistitan** [comment]
Hi @Ezra,

Thanks a lot for opening this report.
Unfortunately, I have to say this change was intentional.
 
The image sharing feature was the only benefit the Android App had compared to the web version. However, the new version that is ported from the web has quite some benefits over the previous one:
- Android Inbox and web version now sync perfectly and in real-time.
- Added features like Delete, Archive, Report, Block and see when someone is typing.
- No more caching issues (delete/archived conversations stayed inside the Android app).
- Added a filter to toggle between Inbox, All Mail and Archive.
- Showing a replied indicator on conversations where you already replied on.
 
Another benefit of this change is, that starting from now, we only need to maintain one codebase for everything inbox- and conversation-related. Meaning it will be easier to introduce new features in the future.
Should you have any further question or feedback to us, please do not hesitate to let us know!

**Comment by kistitan** [comment]
Closing this issue as it works as design at the moment.

We still added note about request to support image sharing in the future.
