### ISSUE TITLE
Friend List Searching

### ISSUE THREAD

**Issue by Daddy** [fetlife/android#57]
For many individuals, there are many who have far too many friends so with the addition of the friends list it has become unusuable due to the need to scroll through an entire list of friends to find the right user. This leads to a very frustrating user experience overall and can also cause non-loading friends lists entirely if the device has a bad connection.

**Improvements**
To improve this, I would firstly store a copy of the entire friends list on the local DB and apply updates on it whenever a new friend is added, or otherwise invalidate the data after a set period of time. Secondly, order the list alphabetically to match Fetlife's organization and then add a alphabetical scroll so that you can quickly navigate to users by letter, or numbers/symbols.

**Goals**
Improve overall user experience while searching for users, and make searching for a user a breeze.

**Comment by kistitan** [comment]
Friends are already stored in the database but indeed they added to the db dynamically as they has been browsed through.

As I see we have twp feature request here:
- Notify the Android app each time a new friend added / removed so it can maintain the friend list
- Add search functionality to the friend list

The second is an absolutely valid request, it is already on our list
The first one is valid two however it needs some more consideration.

None of the feature can be expected before the upcoming version 1.0, but we will keep discussing an working on them

**Comment by smiller171** [comment]
@kistitan you wouldn't need to do a notification, just trigger a download when the user tries to interact with the friends list in the app.

**Comment by kistitan** [comment]
@smiller171 
Yep sure you are right. 

I was just thinking it a bit further. 

If we plan to have the rely only the db version of the friend list without regular update, it would mean we should maintain it. 
We can do it the way you suggest downloading all the friends each time the user interacts, but it would mean for some downloading the details for thousand of people that could end up in poor user experience.
Other option would be instead of downloading it maintain via notification so add/remove friends individually when there is a change. This could increase a lot the performance and reduce the wait time for friend list. Especially with poor connection.

But this notification we need otherwise anyway for other features too.

**Comment by kistitan** [comment]
General Member search has been implemented in latest release.
